name: course_selling_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  # cloud_firestore: ^4.8.0
  bloc: ^8.1.2
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  # intl: ^0.18.1
  flutter_test:
    sdk: flutter
  meta: ^1.9.1

  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  theme_tailor: ^2.0.0
  test: ^1.24.1

flutter:
  assets:
    - assets/images/welcome/
    - assets/icons/

  uses-material-design: true
